services:
  api-gateway:
    image: api-gateway
    pull_policy: never
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    command: ["/app/api-gateway"]
    depends_on:
      - todo-service
    ports:
      - "3000:3000"
    networks:
      - local

  todo-service:
    image: todo-service
    pull_policy: never
    build:
      context: ./todo
      dockerfile: Dockerfile
    depends_on:
      - db
    command: ["/app/todo"]
    networks:
      - local

  db:
    image: mysql:8.0-oracle
    environment:
      command: --default-authentication-plugin=mysql_native_password
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo
    volumes:
      - ./todo/mount/mysql-data:/var/lib/mysql
      - ./todo/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    networks:
      - local

networks:
  local:
    driver: bridge
