root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."

# Binary file yields from `cmd`.
bin = "tmp/main"

# Watch these filename extensions.
include_ext = ["go"]

# Ignore these filename extensions or directories.
exclude_dir = [".git", "tmp", ".md", "build", "migration", ".sql", "mount", "mysql"]

# This log file places in your tmp_dir.
log = "air.log"

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

# Stop running old binary when build errors occur.
stop_on_error = true

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true

# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true


### CONFIG MORE HERE
#https://github.com/cosmtrek/air/blob/master/air_example.toml